name: Check Boxes Are Checked

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-is-ready:
    name: PR Is Ready
    # You do not appear to be able to use variables in the "uses" field.
    uses: NRLMMD-GEOIPS/geoips_ci/.github/workflows/reusable-pr-check-boxes-complete.yaml@main
    permissions:
      contents: read
